apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ninjacat-test-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ninjacat-test.archer.software`)
      kind: Rule
      services:
        - name: ninjacat-test-service
          port: 8765
  tls:
    certResolver: cloudflare
